
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

homeassistant:
  name: Home
  unit_system: metric
  time_zone: Australia/Brisbane

device_tracker:
  - platform: netgear
    password: !secret routerpassword

light:
  - platform: group
    name: Living Room
    entities:
      - light.living_room
      - light.hue_lightstrip
  - platform: group
    name: Bedroom
    entities:
      - light.martin_s_side
      - light.nandar_s_side

panel_iframe:
  nas:
    title: 'NAS'
    url: !secret nasurl
    icon: 'mdi:amazon-drive'
  transmission:
    title: 'Transmission'
    url: !secret transmissionurl
    icon: 'mdi:progress-download'

spotify:
  client_id: !secret spotifyclientid
  client_secret: !secret spotifyclientsecret

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
