name: Check Home Assistant configuration

on: [push]

jobs:
  check-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Install python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install homeassistant
      - name: Copy secrets
        run: mv secrets.sample.yaml secrets.yaml
      - name: Check configuration
        run: hass -c . --script check_config


